
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.debug.autogen_debug_ctx_def_h
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

HPy debug_ctx_Module_Create(HPyContext ctx, HPyModuleDef *def);
HPy debug_ctx_Dup(HPyContext ctx, HPy h);
void debug_ctx_Close(HPyContext ctx, HPy h);
HPy debug_ctx_Long_FromLong(HPyContext ctx, long value);
HPy debug_ctx_Long_FromUnsignedLong(HPyContext ctx, unsigned long value);
HPy debug_ctx_Long_FromLongLong(HPyContext ctx, long long v);
HPy debug_ctx_Long_FromUnsignedLongLong(HPyContext ctx, unsigned long long v);
HPy debug_ctx_Long_FromSize_t(HPyContext ctx, size_t value);
HPy debug_ctx_Long_FromSsize_t(HPyContext ctx, HPy_ssize_t value);
long debug_ctx_Long_AsLong(HPyContext ctx, HPy h);
unsigned long debug_ctx_Long_AsUnsignedLong(HPyContext ctx, HPy h);
unsigned long debug_ctx_Long_AsUnsignedLongMask(HPyContext ctx, HPy h);
long long debug_ctx_Long_AsLongLong(HPyContext ctx, HPy h);
unsigned long long debug_ctx_Long_AsUnsignedLongLong(HPyContext ctx, HPy h);
unsigned long long debug_ctx_Long_AsUnsignedLongLongMask(HPyContext ctx, HPy h);
size_t debug_ctx_Long_AsSize_t(HPyContext ctx, HPy h);
HPy_ssize_t debug_ctx_Long_AsSsize_t(HPyContext ctx, HPy h);
HPy debug_ctx_Float_FromDouble(HPyContext ctx, double v);
double debug_ctx_Float_AsDouble(HPyContext ctx, HPy h);
HPy_ssize_t debug_ctx_Length(HPyContext ctx, HPy h);
int debug_ctx_Number_Check(HPyContext ctx, HPy h);
HPy debug_ctx_Add(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Subtract(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Multiply(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_MatrixMultiply(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_FloorDivide(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_TrueDivide(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Remainder(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Divmod(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Power(HPyContext ctx, HPy h1, HPy h2, HPy h3);
HPy debug_ctx_Negative(HPyContext ctx, HPy h1);
HPy debug_ctx_Positive(HPyContext ctx, HPy h1);
HPy debug_ctx_Absolute(HPyContext ctx, HPy h1);
HPy debug_ctx_Invert(HPyContext ctx, HPy h1);
HPy debug_ctx_Lshift(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Rshift(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_And(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Xor(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Or(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_Index(HPyContext ctx, HPy h1);
HPy debug_ctx_Long(HPyContext ctx, HPy h1);
HPy debug_ctx_Float(HPyContext ctx, HPy h1);
HPy debug_ctx_InPlaceAdd(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceSubtract(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceMultiply(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceMatrixMultiply(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceFloorDivide(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceTrueDivide(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceRemainder(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlacePower(HPyContext ctx, HPy h1, HPy h2, HPy h3);
HPy debug_ctx_InPlaceLshift(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceRshift(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceAnd(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceXor(HPyContext ctx, HPy h1, HPy h2);
HPy debug_ctx_InPlaceOr(HPyContext ctx, HPy h1, HPy h2);
void debug_ctx_Err_SetString(HPyContext ctx, HPy h_type, const char *message);
void debug_ctx_Err_SetObject(HPyContext ctx, HPy h_type, HPy h_value);
int debug_ctx_Err_Occurred(HPyContext ctx);
HPy debug_ctx_Err_NoMemory(HPyContext ctx);
void debug_ctx_Err_Clear(HPyContext ctx);
int debug_ctx_IsTrue(HPyContext ctx, HPy h);
HPy debug_ctx_Type_FromSpec(HPyContext ctx, HPyType_Spec *spec, HPyType_SpecParam *params);
HPy debug_ctx_Type_GenericNew(HPyContext ctx, HPy type, HPy *args, HPy_ssize_t nargs, HPy kw);
HPy debug_ctx_GetAttr(HPyContext ctx, HPy obj, HPy name);
HPy debug_ctx_GetAttr_s(HPyContext ctx, HPy obj, const char *name);
int debug_ctx_HasAttr(HPyContext ctx, HPy obj, HPy name);
int debug_ctx_HasAttr_s(HPyContext ctx, HPy obj, const char *name);
int debug_ctx_SetAttr(HPyContext ctx, HPy obj, HPy name, HPy value);
int debug_ctx_SetAttr_s(HPyContext ctx, HPy obj, const char *name, HPy value);
HPy debug_ctx_GetItem(HPyContext ctx, HPy obj, HPy key);
HPy debug_ctx_GetItem_i(HPyContext ctx, HPy obj, HPy_ssize_t idx);
HPy debug_ctx_GetItem_s(HPyContext ctx, HPy obj, const char *key);
int debug_ctx_SetItem(HPyContext ctx, HPy obj, HPy key, HPy value);
int debug_ctx_SetItem_i(HPyContext ctx, HPy obj, HPy_ssize_t idx, HPy value);
int debug_ctx_SetItem_s(HPyContext ctx, HPy obj, const char *key, HPy value);
void *debug_ctx_Cast(HPyContext ctx, HPy h);
HPy debug_ctx_New(HPyContext ctx, HPy h_type, void **data);
HPy debug_ctx_Repr(HPyContext ctx, HPy obj);
HPy debug_ctx_Str(HPyContext ctx, HPy obj);
HPy debug_ctx_ASCII(HPyContext ctx, HPy obj);
HPy debug_ctx_Bytes(HPyContext ctx, HPy obj);
HPy debug_ctx_RichCompare(HPyContext ctx, HPy v, HPy w, int op);
int debug_ctx_RichCompareBool(HPyContext ctx, HPy v, HPy w, int op);
HPy_hash_t debug_ctx_Hash(HPyContext ctx, HPy obj);
int debug_ctx_Bytes_Check(HPyContext ctx, HPy h);
HPy_ssize_t debug_ctx_Bytes_Size(HPyContext ctx, HPy h);
HPy_ssize_t debug_ctx_Bytes_GET_SIZE(HPyContext ctx, HPy h);
char *debug_ctx_Bytes_AsString(HPyContext ctx, HPy h);
char *debug_ctx_Bytes_AS_STRING(HPyContext ctx, HPy h);
HPy debug_ctx_Bytes_FromString(HPyContext ctx, const char *v);
HPy debug_ctx_Bytes_FromStringAndSize(HPyContext ctx, const char *v, HPy_ssize_t len);
HPy debug_ctx_Unicode_FromString(HPyContext ctx, const char *utf8);
int debug_ctx_Unicode_Check(HPyContext ctx, HPy h);
HPy debug_ctx_Unicode_AsUTF8String(HPyContext ctx, HPy h);
HPy debug_ctx_Unicode_FromWideChar(HPyContext ctx, const wchar_t *w, HPy_ssize_t size);
int debug_ctx_List_Check(HPyContext ctx, HPy h);
HPy debug_ctx_List_New(HPyContext ctx, HPy_ssize_t len);
int debug_ctx_List_Append(HPyContext ctx, HPy h_list, HPy h_item);
int debug_ctx_Dict_Check(HPyContext ctx, HPy h);
HPy debug_ctx_Dict_New(HPyContext ctx);
void debug_ctx_FatalError(HPyContext ctx, const char *message);
HPy debug_ctx_Tuple_FromArray(HPyContext ctx, HPy items[], HPy_ssize_t n);
HPy debug_ctx_FromPyObject(HPyContext ctx, cpy_PyObject *obj);
cpy_PyObject *debug_ctx_AsPyObject(HPyContext ctx, HPy h);
void debug_ctx_CallRealFunctionFromTrampoline(HPyContext ctx, HPyFunc_Signature sig, void *func, void *args);
void debug_ctx_CallDestroyAndThenDealloc(HPyContext ctx, void *func, cpy_PyObject *self);
HPyListBuilder debug_ctx_ListBuilder_New(HPyContext ctx, HPy_ssize_t initial_size);
void debug_ctx_ListBuilder_Set(HPyContext ctx, HPyListBuilder builder, HPy_ssize_t index, HPy h_item);
HPy debug_ctx_ListBuilder_Build(HPyContext ctx, HPyListBuilder builder);
void debug_ctx_ListBuilder_Cancel(HPyContext ctx, HPyListBuilder builder);
HPyTupleBuilder debug_ctx_TupleBuilder_New(HPyContext ctx, HPy_ssize_t initial_size);
void debug_ctx_TupleBuilder_Set(HPyContext ctx, HPyTupleBuilder builder, HPy_ssize_t index, HPy h_item);
HPy debug_ctx_TupleBuilder_Build(HPyContext ctx, HPyTupleBuilder builder);
void debug_ctx_TupleBuilder_Cancel(HPyContext ctx, HPyTupleBuilder builder);
HPyTracker debug_ctx_Tracker_New(HPyContext ctx, HPy_ssize_t size);
int debug_ctx_Tracker_Add(HPyContext ctx, HPyTracker ht, HPy h);
void debug_ctx_Tracker_ForgetAll(HPyContext ctx, HPyTracker ht);
void debug_ctx_Tracker_Close(HPyContext ctx, HPyTracker ht);

static struct _HPyContext_s g_debug_ctx = {
    .name = "HPy Debug Mode ABI",
    ._private = NULL,
    .ctx_version = 1,
    .h_None = HPy_NULL,
    .h_True = HPy_NULL,
    .h_False = HPy_NULL,
    .h_BaseException = HPy_NULL,
    .h_Exception = HPy_NULL,
    .h_StopAsyncIteration = HPy_NULL,
    .h_StopIteration = HPy_NULL,
    .h_GeneratorExit = HPy_NULL,
    .h_ArithmeticError = HPy_NULL,
    .h_LookupError = HPy_NULL,
    .h_AssertionError = HPy_NULL,
    .h_AttributeError = HPy_NULL,
    .h_BufferError = HPy_NULL,
    .h_EOFError = HPy_NULL,
    .h_FloatingPointError = HPy_NULL,
    .h_OSError = HPy_NULL,
    .h_ImportError = HPy_NULL,
    .h_ModuleNotFoundError = HPy_NULL,
    .h_IndexError = HPy_NULL,
    .h_KeyError = HPy_NULL,
    .h_KeyboardInterrupt = HPy_NULL,
    .h_MemoryError = HPy_NULL,
    .h_NameError = HPy_NULL,
    .h_OverflowError = HPy_NULL,
    .h_RuntimeError = HPy_NULL,
    .h_RecursionError = HPy_NULL,
    .h_NotImplementedError = HPy_NULL,
    .h_SyntaxError = HPy_NULL,
    .h_IndentationError = HPy_NULL,
    .h_TabError = HPy_NULL,
    .h_ReferenceError = HPy_NULL,
    .h_SystemError = HPy_NULL,
    .h_SystemExit = HPy_NULL,
    .h_TypeError = HPy_NULL,
    .h_UnboundLocalError = HPy_NULL,
    .h_UnicodeError = HPy_NULL,
    .h_UnicodeEncodeError = HPy_NULL,
    .h_UnicodeDecodeError = HPy_NULL,
    .h_UnicodeTranslateError = HPy_NULL,
    .h_ValueError = HPy_NULL,
    .h_ZeroDivisionError = HPy_NULL,
    .h_BlockingIOError = HPy_NULL,
    .h_BrokenPipeError = HPy_NULL,
    .h_ChildProcessError = HPy_NULL,
    .h_ConnectionError = HPy_NULL,
    .h_ConnectionAbortedError = HPy_NULL,
    .h_ConnectionRefusedError = HPy_NULL,
    .h_ConnectionResetError = HPy_NULL,
    .h_FileExistsError = HPy_NULL,
    .h_FileNotFoundError = HPy_NULL,
    .h_InterruptedError = HPy_NULL,
    .h_IsADirectoryError = HPy_NULL,
    .h_NotADirectoryError = HPy_NULL,
    .h_PermissionError = HPy_NULL,
    .h_ProcessLookupError = HPy_NULL,
    .h_TimeoutError = HPy_NULL,
    .h_Warning = HPy_NULL,
    .h_UserWarning = HPy_NULL,
    .h_DeprecationWarning = HPy_NULL,
    .h_PendingDeprecationWarning = HPy_NULL,
    .h_SyntaxWarning = HPy_NULL,
    .h_RuntimeWarning = HPy_NULL,
    .h_FutureWarning = HPy_NULL,
    .h_ImportWarning = HPy_NULL,
    .h_UnicodeWarning = HPy_NULL,
    .h_BytesWarning = HPy_NULL,
    .h_ResourceWarning = HPy_NULL,
    .h_BaseObjectType = HPy_NULL,
    .h_TypeType = HPy_NULL,
    .h_LongType = HPy_NULL,
    .h_UnicodeType = HPy_NULL,
    .h_TupleType = HPy_NULL,
    .h_ListType = HPy_NULL,
    .ctx_Module_Create = &debug_ctx_Module_Create,
    .ctx_Dup = &debug_ctx_Dup,
    .ctx_Close = &debug_ctx_Close,
    .ctx_Long_FromLong = &debug_ctx_Long_FromLong,
    .ctx_Long_FromUnsignedLong = &debug_ctx_Long_FromUnsignedLong,
    .ctx_Long_FromLongLong = &debug_ctx_Long_FromLongLong,
    .ctx_Long_FromUnsignedLongLong = &debug_ctx_Long_FromUnsignedLongLong,
    .ctx_Long_FromSize_t = &debug_ctx_Long_FromSize_t,
    .ctx_Long_FromSsize_t = &debug_ctx_Long_FromSsize_t,
    .ctx_Long_AsLong = &debug_ctx_Long_AsLong,
    .ctx_Long_AsUnsignedLong = &debug_ctx_Long_AsUnsignedLong,
    .ctx_Long_AsUnsignedLongMask = &debug_ctx_Long_AsUnsignedLongMask,
    .ctx_Long_AsLongLong = &debug_ctx_Long_AsLongLong,
    .ctx_Long_AsUnsignedLongLong = &debug_ctx_Long_AsUnsignedLongLong,
    .ctx_Long_AsUnsignedLongLongMask = &debug_ctx_Long_AsUnsignedLongLongMask,
    .ctx_Long_AsSize_t = &debug_ctx_Long_AsSize_t,
    .ctx_Long_AsSsize_t = &debug_ctx_Long_AsSsize_t,
    .ctx_Float_FromDouble = &debug_ctx_Float_FromDouble,
    .ctx_Float_AsDouble = &debug_ctx_Float_AsDouble,
    .ctx_Length = &debug_ctx_Length,
    .ctx_Number_Check = &debug_ctx_Number_Check,
    .ctx_Add = &debug_ctx_Add,
    .ctx_Subtract = &debug_ctx_Subtract,
    .ctx_Multiply = &debug_ctx_Multiply,
    .ctx_MatrixMultiply = &debug_ctx_MatrixMultiply,
    .ctx_FloorDivide = &debug_ctx_FloorDivide,
    .ctx_TrueDivide = &debug_ctx_TrueDivide,
    .ctx_Remainder = &debug_ctx_Remainder,
    .ctx_Divmod = &debug_ctx_Divmod,
    .ctx_Power = &debug_ctx_Power,
    .ctx_Negative = &debug_ctx_Negative,
    .ctx_Positive = &debug_ctx_Positive,
    .ctx_Absolute = &debug_ctx_Absolute,
    .ctx_Invert = &debug_ctx_Invert,
    .ctx_Lshift = &debug_ctx_Lshift,
    .ctx_Rshift = &debug_ctx_Rshift,
    .ctx_And = &debug_ctx_And,
    .ctx_Xor = &debug_ctx_Xor,
    .ctx_Or = &debug_ctx_Or,
    .ctx_Index = &debug_ctx_Index,
    .ctx_Long = &debug_ctx_Long,
    .ctx_Float = &debug_ctx_Float,
    .ctx_InPlaceAdd = &debug_ctx_InPlaceAdd,
    .ctx_InPlaceSubtract = &debug_ctx_InPlaceSubtract,
    .ctx_InPlaceMultiply = &debug_ctx_InPlaceMultiply,
    .ctx_InPlaceMatrixMultiply = &debug_ctx_InPlaceMatrixMultiply,
    .ctx_InPlaceFloorDivide = &debug_ctx_InPlaceFloorDivide,
    .ctx_InPlaceTrueDivide = &debug_ctx_InPlaceTrueDivide,
    .ctx_InPlaceRemainder = &debug_ctx_InPlaceRemainder,
    .ctx_InPlacePower = &debug_ctx_InPlacePower,
    .ctx_InPlaceLshift = &debug_ctx_InPlaceLshift,
    .ctx_InPlaceRshift = &debug_ctx_InPlaceRshift,
    .ctx_InPlaceAnd = &debug_ctx_InPlaceAnd,
    .ctx_InPlaceXor = &debug_ctx_InPlaceXor,
    .ctx_InPlaceOr = &debug_ctx_InPlaceOr,
    .ctx_Err_SetString = &debug_ctx_Err_SetString,
    .ctx_Err_SetObject = &debug_ctx_Err_SetObject,
    .ctx_Err_Occurred = &debug_ctx_Err_Occurred,
    .ctx_Err_NoMemory = &debug_ctx_Err_NoMemory,
    .ctx_Err_Clear = &debug_ctx_Err_Clear,
    .ctx_IsTrue = &debug_ctx_IsTrue,
    .ctx_Type_FromSpec = &debug_ctx_Type_FromSpec,
    .ctx_Type_GenericNew = &debug_ctx_Type_GenericNew,
    .ctx_GetAttr = &debug_ctx_GetAttr,
    .ctx_GetAttr_s = &debug_ctx_GetAttr_s,
    .ctx_HasAttr = &debug_ctx_HasAttr,
    .ctx_HasAttr_s = &debug_ctx_HasAttr_s,
    .ctx_SetAttr = &debug_ctx_SetAttr,
    .ctx_SetAttr_s = &debug_ctx_SetAttr_s,
    .ctx_GetItem = &debug_ctx_GetItem,
    .ctx_GetItem_i = &debug_ctx_GetItem_i,
    .ctx_GetItem_s = &debug_ctx_GetItem_s,
    .ctx_SetItem = &debug_ctx_SetItem,
    .ctx_SetItem_i = &debug_ctx_SetItem_i,
    .ctx_SetItem_s = &debug_ctx_SetItem_s,
    .ctx_Cast = &debug_ctx_Cast,
    .ctx_New = &debug_ctx_New,
    .ctx_Repr = &debug_ctx_Repr,
    .ctx_Str = &debug_ctx_Str,
    .ctx_ASCII = &debug_ctx_ASCII,
    .ctx_Bytes = &debug_ctx_Bytes,
    .ctx_RichCompare = &debug_ctx_RichCompare,
    .ctx_RichCompareBool = &debug_ctx_RichCompareBool,
    .ctx_Hash = &debug_ctx_Hash,
    .ctx_Bytes_Check = &debug_ctx_Bytes_Check,
    .ctx_Bytes_Size = &debug_ctx_Bytes_Size,
    .ctx_Bytes_GET_SIZE = &debug_ctx_Bytes_GET_SIZE,
    .ctx_Bytes_AsString = &debug_ctx_Bytes_AsString,
    .ctx_Bytes_AS_STRING = &debug_ctx_Bytes_AS_STRING,
    .ctx_Bytes_FromString = &debug_ctx_Bytes_FromString,
    .ctx_Bytes_FromStringAndSize = &debug_ctx_Bytes_FromStringAndSize,
    .ctx_Unicode_FromString = &debug_ctx_Unicode_FromString,
    .ctx_Unicode_Check = &debug_ctx_Unicode_Check,
    .ctx_Unicode_AsUTF8String = &debug_ctx_Unicode_AsUTF8String,
    .ctx_Unicode_FromWideChar = &debug_ctx_Unicode_FromWideChar,
    .ctx_List_Check = &debug_ctx_List_Check,
    .ctx_List_New = &debug_ctx_List_New,
    .ctx_List_Append = &debug_ctx_List_Append,
    .ctx_Dict_Check = &debug_ctx_Dict_Check,
    .ctx_Dict_New = &debug_ctx_Dict_New,
    .ctx_FatalError = &debug_ctx_FatalError,
    .ctx_Tuple_FromArray = &debug_ctx_Tuple_FromArray,
    .ctx_FromPyObject = &debug_ctx_FromPyObject,
    .ctx_AsPyObject = &debug_ctx_AsPyObject,
    .ctx_CallRealFunctionFromTrampoline = &debug_ctx_CallRealFunctionFromTrampoline,
    .ctx_CallDestroyAndThenDealloc = &debug_ctx_CallDestroyAndThenDealloc,
    .ctx_ListBuilder_New = &debug_ctx_ListBuilder_New,
    .ctx_ListBuilder_Set = &debug_ctx_ListBuilder_Set,
    .ctx_ListBuilder_Build = &debug_ctx_ListBuilder_Build,
    .ctx_ListBuilder_Cancel = &debug_ctx_ListBuilder_Cancel,
    .ctx_TupleBuilder_New = &debug_ctx_TupleBuilder_New,
    .ctx_TupleBuilder_Set = &debug_ctx_TupleBuilder_Set,
    .ctx_TupleBuilder_Build = &debug_ctx_TupleBuilder_Build,
    .ctx_TupleBuilder_Cancel = &debug_ctx_TupleBuilder_Cancel,
    .ctx_Tracker_New = &debug_ctx_Tracker_New,
    .ctx_Tracker_Add = &debug_ctx_Tracker_Add,
    .ctx_Tracker_ForgetAll = &debug_ctx_Tracker_ForgetAll,
    .ctx_Tracker_Close = &debug_ctx_Tracker_Close,
};
