
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.trace.autogen_tracer_wrappers
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

#include "trace_internal.h"

HPy trace_ctx_Module_Create(HPyContext *tctx, HPyModuleDef *def)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[77]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyModule_Create(tctx_info->uctx, def);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[77] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Dup(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[78]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Dup(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[78] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Close(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[79]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_Close(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[79] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_Long_FromLong(HPyContext *tctx, long value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[80]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyLong_FromLong(tctx_info->uctx, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[80] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Long_FromUnsignedLong(HPyContext *tctx, unsigned long value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[81]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyLong_FromUnsignedLong(tctx_info->uctx, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[81] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Long_FromLongLong(HPyContext *tctx, long long v)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[82]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyLong_FromLongLong(tctx_info->uctx, v);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[82] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Long_FromUnsignedLongLong(HPyContext *tctx, unsigned long long v)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[83]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyLong_FromUnsignedLongLong(tctx_info->uctx, v);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[83] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Long_FromSize_t(HPyContext *tctx, size_t value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[84]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyLong_FromSize_t(tctx_info->uctx, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[84] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Long_FromSsize_t(HPyContext *tctx, HPy_ssize_t value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[85]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyLong_FromSsize_t(tctx_info->uctx, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[85] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

long trace_ctx_Long_AsLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[86]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    long res = HPyLong_AsLong(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[86] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

unsigned long trace_ctx_Long_AsUnsignedLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[87]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    unsigned long res = HPyLong_AsUnsignedLong(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[87] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

unsigned long trace_ctx_Long_AsUnsignedLongMask(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[88]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    unsigned long res = HPyLong_AsUnsignedLongMask(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[88] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

long long trace_ctx_Long_AsLongLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[89]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    long long res = HPyLong_AsLongLong(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[89] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

unsigned long long trace_ctx_Long_AsUnsignedLongLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[90]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    unsigned long long res = HPyLong_AsUnsignedLongLong(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[90] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

unsigned long long trace_ctx_Long_AsUnsignedLongLongMask(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[91]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    unsigned long long res = HPyLong_AsUnsignedLongLongMask(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[91] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

size_t trace_ctx_Long_AsSize_t(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[92]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    size_t res = HPyLong_AsSize_t(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[92] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy_ssize_t trace_ctx_Long_AsSsize_t(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[93]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_ssize_t res = HPyLong_AsSsize_t(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[93] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_Long_AsVoidPtr(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[94]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = HPyLong_AsVoidPtr(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[94] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

double trace_ctx_Long_AsDouble(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[95]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    double res = HPyLong_AsDouble(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[95] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Float_FromDouble(HPyContext *tctx, double v)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[96]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyFloat_FromDouble(tctx_info->uctx, v);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[96] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

double trace_ctx_Float_AsDouble(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[97]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    double res = HPyFloat_AsDouble(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[97] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Bool_FromLong(HPyContext *tctx, long v)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[98]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyBool_FromLong(tctx_info->uctx, v);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[98] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy_ssize_t trace_ctx_Length(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[99]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_ssize_t res = HPy_Length(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[99] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Number_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[100]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyNumber_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[100] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Add(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[101]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Add(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[101] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Subtract(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[102]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Subtract(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[102] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Multiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[103]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Multiply(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[103] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_MatrixMultiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[104]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_MatrixMultiply(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[104] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_FloorDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[105]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_FloorDivide(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[105] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_TrueDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[106]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_TrueDivide(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[106] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Remainder(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[107]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Remainder(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[107] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Divmod(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[108]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Divmod(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[108] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Power(HPyContext *tctx, HPy h1, HPy h2, HPy h3)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[109]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Power(tctx_info->uctx, h1, h2, h3);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[109] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Negative(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[110]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Negative(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[110] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Positive(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[111]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Positive(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[111] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Absolute(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[112]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Absolute(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[112] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Invert(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[113]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Invert(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[113] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Lshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[114]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Lshift(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[114] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Rshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[115]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Rshift(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[115] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_And(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[116]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_And(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[116] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Xor(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[117]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Xor(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[117] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Or(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[118]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Or(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[118] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Index(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[119]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Index(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[119] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Long(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[120]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Long(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[120] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Float(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[121]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Float(tctx_info->uctx, h1);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[121] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceAdd(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[122]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceAdd(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[122] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceSubtract(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[123]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceSubtract(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[123] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceMultiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[124]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceMultiply(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[124] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceMatrixMultiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[125]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceMatrixMultiply(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[125] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceFloorDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[126]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceFloorDivide(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[126] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceTrueDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[127]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceTrueDivide(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[127] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceRemainder(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[128]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceRemainder(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[128] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlacePower(HPyContext *tctx, HPy h1, HPy h2, HPy h3)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[129]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlacePower(tctx_info->uctx, h1, h2, h3);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[129] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceLshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[130]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceLshift(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[130] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceRshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[131]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceRshift(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[131] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceAnd(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[132]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceAnd(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[132] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceXor(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[133]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceXor(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[133] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_InPlaceOr(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[134]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_InPlaceOr(tctx_info->uctx, h1, h2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[134] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Callable_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[135]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyCallable_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[135] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_CallTupleDict(HPyContext *tctx, HPy callable, HPy args, HPy kw)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[136]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_CallTupleDict(tctx_info->uctx, callable, args, kw);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[136] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_FatalError(HPyContext *tctx, const char *message)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[137]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_FatalError(tctx_info->uctx, message);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[137] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

void trace_ctx_Err_SetString(HPyContext *tctx, HPy h_type, const char *message)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[138]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyErr_SetString(tctx_info->uctx, h_type, message);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[138] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

void trace_ctx_Err_SetObject(HPyContext *tctx, HPy h_type, HPy h_value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[139]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyErr_SetObject(tctx_info->uctx, h_type, h_value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[139] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_Err_SetFromErrnoWithFilename(HPyContext *tctx, HPy h_type, const char *filename_fsencoded)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[140]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyErr_SetFromErrnoWithFilename(tctx_info->uctx, h_type, filename_fsencoded);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[140] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Err_SetFromErrnoWithFilenameObjects(HPyContext *tctx, HPy h_type, HPy filename1, HPy filename2)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[141]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyErr_SetFromErrnoWithFilenameObjects(tctx_info->uctx, h_type, filename1, filename2);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[141] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

int trace_ctx_Err_Occurred(HPyContext *tctx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[142]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyErr_Occurred(tctx_info->uctx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[142] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Err_ExceptionMatches(HPyContext *tctx, HPy exc)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[143]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyErr_ExceptionMatches(tctx_info->uctx, exc);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[143] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Err_NoMemory(HPyContext *tctx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[144]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyErr_NoMemory(tctx_info->uctx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[144] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

void trace_ctx_Err_Clear(HPyContext *tctx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[145]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyErr_Clear(tctx_info->uctx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[145] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_Err_NewException(HPyContext *tctx, const char *name, HPy base, HPy dict)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[146]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyErr_NewException(tctx_info->uctx, name, base, dict);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[146] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Err_NewExceptionWithDoc(HPyContext *tctx, const char *name, const char *doc, HPy base, HPy dict)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[147]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyErr_NewExceptionWithDoc(tctx_info->uctx, name, doc, base, dict);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[147] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Err_WarnEx(HPyContext *tctx, HPy category, const char *message, HPy_ssize_t stack_level)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[148]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyErr_WarnEx(tctx_info->uctx, category, message, stack_level);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[148] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Err_WriteUnraisable(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[149]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyErr_WriteUnraisable(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[149] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

int trace_ctx_IsTrue(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[150]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_IsTrue(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[150] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Type_FromSpec(HPyContext *tctx, HPyType_Spec *spec, HPyType_SpecParam *params)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[151]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyType_FromSpec(tctx_info->uctx, spec, params);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[151] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Type_GenericNew(HPyContext *tctx, HPy type, HPy *args, HPy_ssize_t nargs, HPy kw)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[152]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyType_GenericNew(tctx_info->uctx, type, args, nargs, kw);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[152] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_GetAttr(HPyContext *tctx, HPy obj, HPy name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[153]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_GetAttr(tctx_info->uctx, obj, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[153] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_GetAttr_s(HPyContext *tctx, HPy obj, const char *name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[154]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_GetAttr_s(tctx_info->uctx, obj, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[154] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_HasAttr(HPyContext *tctx, HPy obj, HPy name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[155]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_HasAttr(tctx_info->uctx, obj, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[155] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_HasAttr_s(HPyContext *tctx, HPy obj, const char *name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[156]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_HasAttr_s(tctx_info->uctx, obj, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[156] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_SetAttr(HPyContext *tctx, HPy obj, HPy name, HPy value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[157]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_SetAttr(tctx_info->uctx, obj, name, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[157] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_SetAttr_s(HPyContext *tctx, HPy obj, const char *name, HPy value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[158]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_SetAttr_s(tctx_info->uctx, obj, name, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[158] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_GetItem(HPyContext *tctx, HPy obj, HPy key)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[159]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_GetItem(tctx_info->uctx, obj, key);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[159] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_GetItem_i(HPyContext *tctx, HPy obj, HPy_ssize_t idx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[160]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_GetItem_i(tctx_info->uctx, obj, idx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[160] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_GetItem_s(HPyContext *tctx, HPy obj, const char *key)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[161]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_GetItem_s(tctx_info->uctx, obj, key);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[161] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Contains(HPyContext *tctx, HPy container, HPy key)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[162]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_Contains(tctx_info->uctx, container, key);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[162] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_SetItem(HPyContext *tctx, HPy obj, HPy key, HPy value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[163]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_SetItem(tctx_info->uctx, obj, key, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[163] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_SetItem_i(HPyContext *tctx, HPy obj, HPy_ssize_t idx, HPy value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[164]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_SetItem_i(tctx_info->uctx, obj, idx, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[164] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_SetItem_s(HPyContext *tctx, HPy obj, const char *key, HPy value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[165]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_SetItem_s(tctx_info->uctx, obj, key, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[165] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_DelItem(HPyContext *tctx, HPy obj, HPy key)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[236]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_DelItem(tctx_info->uctx, obj, key);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[236] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_DelItem_i(HPyContext *tctx, HPy obj, HPy_ssize_t idx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[237]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_DelItem_i(tctx_info->uctx, obj, idx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[237] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_DelItem_s(HPyContext *tctx, HPy obj, const char *key)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[238]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_DelItem_s(tctx_info->uctx, obj, key);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[238] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Type(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[166]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Type(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[166] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_TypeCheck(HPyContext *tctx, HPy obj, HPy type)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[167]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_TypeCheck(tctx_info->uctx, obj, type);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[167] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Is(HPyContext *tctx, HPy obj, HPy other)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[168]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_Is(tctx_info->uctx, obj, other);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[168] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Object(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[169]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Object(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[169] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Legacy(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[170]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Legacy(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[170] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Type(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[229]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Type(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[229] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Long(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[230]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Long(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[230] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Float(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[231]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Float(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[231] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Unicode(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[232]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Unicode(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[232] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_Tuple(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[233]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_Tuple(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[233] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_AsStruct_List(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[234]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = _HPy_AsStruct_List(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[234] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPyType_BuiltinShape trace_ctx_Type_GetBuiltinShape(HPyContext *tctx, HPy h_type)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[235]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyType_BuiltinShape res = _HPyType_GetBuiltinShape(tctx_info->uctx, h_type);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[235] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_New(HPyContext *tctx, HPy h_type, void **data)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[171]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = _HPy_New(tctx_info->uctx, h_type, data);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[171] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Repr(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[172]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Repr(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[172] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Str(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[173]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Str(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[173] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_ASCII(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[174]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_ASCII(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[174] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Bytes(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[175]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_Bytes(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[175] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_RichCompare(HPyContext *tctx, HPy v, HPy w, int op)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[176]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_RichCompare(tctx_info->uctx, v, w, op);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[176] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_RichCompareBool(HPyContext *tctx, HPy v, HPy w, int op)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[177]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPy_RichCompareBool(tctx_info->uctx, v, w, op);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[177] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy_hash_t trace_ctx_Hash(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[178]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_hash_t res = HPy_Hash(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[178] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Bytes_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[179]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyBytes_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[179] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy_ssize_t trace_ctx_Bytes_Size(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[180]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_ssize_t res = HPyBytes_Size(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[180] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy_ssize_t trace_ctx_Bytes_GET_SIZE(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[181]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_ssize_t res = HPyBytes_GET_SIZE(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[181] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

char *trace_ctx_Bytes_AsString(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[182]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    char * res = HPyBytes_AsString(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[182] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

char *trace_ctx_Bytes_AS_STRING(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[183]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    char * res = HPyBytes_AS_STRING(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[183] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Bytes_FromString(HPyContext *tctx, const char *v)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[184]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyBytes_FromString(tctx_info->uctx, v);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[184] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Bytes_FromStringAndSize(HPyContext *tctx, const char *v, HPy_ssize_t len)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[185]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyBytes_FromStringAndSize(tctx_info->uctx, v, len);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[185] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_FromString(HPyContext *tctx, const char *utf8)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[186]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_FromString(tctx_info->uctx, utf8);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[186] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Unicode_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[187]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyUnicode_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[187] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_AsASCIIString(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[188]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_AsASCIIString(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[188] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_AsLatin1String(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[189]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_AsLatin1String(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[189] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_AsUTF8String(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[190]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_AsUTF8String(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[190] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

const char *trace_ctx_Unicode_AsUTF8AndSize(HPyContext *tctx, HPy h, HPy_ssize_t *size)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[191]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    const char * res = HPyUnicode_AsUTF8AndSize(tctx_info->uctx, h, size);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[191] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_FromWideChar(HPyContext *tctx, const wchar_t *w, HPy_ssize_t size)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[192]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_FromWideChar(tctx_info->uctx, w, size);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[192] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_DecodeFSDefault(HPyContext *tctx, const char *v)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[193]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_DecodeFSDefault(tctx_info->uctx, v);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[193] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_DecodeFSDefaultAndSize(HPyContext *tctx, const char *v, HPy_ssize_t size)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[194]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_DecodeFSDefaultAndSize(tctx_info->uctx, v, size);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[194] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_EncodeFSDefault(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[195]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_EncodeFSDefault(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[195] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy_UCS4 trace_ctx_Unicode_ReadChar(HPyContext *tctx, HPy h, HPy_ssize_t index)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[196]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_UCS4 res = HPyUnicode_ReadChar(tctx_info->uctx, h, index);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[196] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_DecodeASCII(HPyContext *tctx, const char *s, HPy_ssize_t size, const char *errors)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[197]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_DecodeASCII(tctx_info->uctx, s, size, errors);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[197] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Unicode_DecodeLatin1(HPyContext *tctx, const char *s, HPy_ssize_t size, const char *errors)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[198]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyUnicode_DecodeLatin1(tctx_info->uctx, s, size, errors);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[198] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_List_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[199]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyList_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[199] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_List_New(HPyContext *tctx, HPy_ssize_t len)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[200]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyList_New(tctx_info->uctx, len);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[200] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_List_Append(HPyContext *tctx, HPy h_list, HPy h_item)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[201]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyList_Append(tctx_info->uctx, h_list, h_item);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[201] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Dict_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[202]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyDict_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[202] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Dict_New(HPyContext *tctx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[203]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyDict_New(tctx_info->uctx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[203] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Tuple_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[204]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyTuple_Check(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[204] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Tuple_FromArray(HPyContext *tctx, HPy items[], HPy_ssize_t n)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[205]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyTuple_FromArray(tctx_info->uctx, items, n);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[205] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Import_ImportModule(HPyContext *tctx, const char *name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[206]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyImport_ImportModule(tctx_info->uctx, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[206] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_Capsule_New(HPyContext *tctx, void *pointer, const char *name, HPyCapsule_Destructor *destructor)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[245]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyCapsule_New(tctx_info->uctx, pointer, name, destructor);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[245] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void *trace_ctx_Capsule_Get(HPyContext *tctx, HPy capsule, _HPyCapsule_key key, const char *name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[246]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    void * res = HPyCapsule_Get(tctx_info->uctx, capsule, key, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[246] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Capsule_IsValid(HPyContext *tctx, HPy capsule, const char *name)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[247]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyCapsule_IsValid(tctx_info->uctx, capsule, name);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[247] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Capsule_Set(HPyContext *tctx, HPy capsule, _HPyCapsule_key key, void *value)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[248]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyCapsule_Set(tctx_info->uctx, capsule, key, value);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[248] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPy trace_ctx_FromPyObject(HPyContext *tctx, cpy_PyObject *obj)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[207]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPy_FromPyObject(tctx_info->uctx, obj);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[207] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

cpy_PyObject *trace_ctx_AsPyObject(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[208]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    cpy_PyObject * res = HPy_AsPyObject(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[208] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

HPyListBuilder trace_ctx_ListBuilder_New(HPyContext *tctx, HPy_ssize_t initial_size)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[210]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyListBuilder res = HPyListBuilder_New(tctx_info->uctx, initial_size);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[210] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_ListBuilder_Set(HPyContext *tctx, HPyListBuilder builder, HPy_ssize_t index, HPy h_item)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[211]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyListBuilder_Set(tctx_info->uctx, builder, index, h_item);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[211] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_ListBuilder_Build(HPyContext *tctx, HPyListBuilder builder)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[212]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyListBuilder_Build(tctx_info->uctx, builder);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[212] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_ListBuilder_Cancel(HPyContext *tctx, HPyListBuilder builder)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[213]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyListBuilder_Cancel(tctx_info->uctx, builder);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[213] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPyTupleBuilder trace_ctx_TupleBuilder_New(HPyContext *tctx, HPy_ssize_t initial_size)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[214]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyTupleBuilder res = HPyTupleBuilder_New(tctx_info->uctx, initial_size);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[214] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_TupleBuilder_Set(HPyContext *tctx, HPyTupleBuilder builder, HPy_ssize_t index, HPy h_item)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[215]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyTupleBuilder_Set(tctx_info->uctx, builder, index, h_item);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[215] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_TupleBuilder_Build(HPyContext *tctx, HPyTupleBuilder builder)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[216]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyTupleBuilder_Build(tctx_info->uctx, builder);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[216] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_TupleBuilder_Cancel(HPyContext *tctx, HPyTupleBuilder builder)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[217]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyTupleBuilder_Cancel(tctx_info->uctx, builder);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[217] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPyTracker trace_ctx_Tracker_New(HPyContext *tctx, HPy_ssize_t size)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[218]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyTracker res = HPyTracker_New(tctx_info->uctx, size);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[218] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

int trace_ctx_Tracker_Add(HPyContext *tctx, HPyTracker ht, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[219]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    int res = HPyTracker_Add(tctx_info->uctx, ht, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[219] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Tracker_ForgetAll(HPyContext *tctx, HPyTracker ht)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[220]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyTracker_ForgetAll(tctx_info->uctx, ht);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[220] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

void trace_ctx_Tracker_Close(HPyContext *tctx, HPyTracker ht)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[221]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyTracker_Close(tctx_info->uctx, ht);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[221] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

void trace_ctx_Field_Store(HPyContext *tctx, HPy target_object, HPyField *target_field, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[222]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyField_Store(tctx_info->uctx, target_object, target_field, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[222] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_Field_Load(HPyContext *tctx, HPy source_object, HPyField source_field)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[223]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyField_Load(tctx_info->uctx, source_object, source_field);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[223] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_ReenterPythonExecution(HPyContext *tctx, HPyThreadState state)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[224]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy_ReenterPythonExecution(tctx_info->uctx, state);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[224] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPyThreadState trace_ctx_LeavePythonExecution(HPyContext *tctx)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[225]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyThreadState res = HPy_LeavePythonExecution(tctx_info->uctx);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[225] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Global_Store(HPyContext *tctx, HPyGlobal *global, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[226]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPyGlobal_Store(tctx_info->uctx, global, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[226] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

HPy trace_ctx_Global_Load(HPyContext *tctx, HPyGlobal global)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[227]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    HPy res = HPyGlobal_Load(tctx_info->uctx, global);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[227] += _ts_end.tv_nsec - _ts_start.tv_nsec;
    return res;
}

void trace_ctx_Dump(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *tctx_info = get_info(tctx);
    struct timespec _ts_start, _ts_end;
    int cr;
    tctx_info->call_counts[228]++;
    cr = clock_gettime(CLOCK_MONOTONIC, &_ts_start);
    _HPy_Dump(tctx_info->uctx, h);
    cr += clock_gettime(CLOCK_MONOTONIC, &_ts_end);
    if (cr)
        HPy_FatalError(tctx_info->uctx, "could not get monotonic clock");
    tctx_info->durations[228] += _ts_end.tv_nsec - _ts_start.tv_nsec;
}

