
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.trace.autogen_tracer_wrappers
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

#include "trace_internal.h"

HPy trace_ctx_Module_Create(HPyContext *tctx, HPyModuleDef *def)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 77);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyModule_Create(uctx, def);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 77, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Dup(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 78);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Dup(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 78, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Close(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 79);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_Close(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 79, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_Long_FromLong(HPyContext *tctx, long value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 80);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyLong_FromLong(uctx, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 80, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Long_FromUnsignedLong(HPyContext *tctx, unsigned long value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 81);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyLong_FromUnsignedLong(uctx, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 81, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Long_FromLongLong(HPyContext *tctx, long long v)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 82);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyLong_FromLongLong(uctx, v);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 82, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Long_FromUnsignedLongLong(HPyContext *tctx, unsigned long long v)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 83);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyLong_FromUnsignedLongLong(uctx, v);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 83, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Long_FromSize_t(HPyContext *tctx, size_t value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 84);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyLong_FromSize_t(uctx, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 84, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Long_FromSsize_t(HPyContext *tctx, HPy_ssize_t value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 85);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyLong_FromSsize_t(uctx, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 85, cr, &_ts_start, &_ts_end);
    return res;
}

long trace_ctx_Long_AsLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 86);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    long res = HPyLong_AsLong(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 86, cr, &_ts_start, &_ts_end);
    return res;
}

unsigned long trace_ctx_Long_AsUnsignedLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 87);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    unsigned long res = HPyLong_AsUnsignedLong(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 87, cr, &_ts_start, &_ts_end);
    return res;
}

unsigned long trace_ctx_Long_AsUnsignedLongMask(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 88);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    unsigned long res = HPyLong_AsUnsignedLongMask(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 88, cr, &_ts_start, &_ts_end);
    return res;
}

long long trace_ctx_Long_AsLongLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 89);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    long long res = HPyLong_AsLongLong(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 89, cr, &_ts_start, &_ts_end);
    return res;
}

unsigned long long trace_ctx_Long_AsUnsignedLongLong(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 90);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    unsigned long long res = HPyLong_AsUnsignedLongLong(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 90, cr, &_ts_start, &_ts_end);
    return res;
}

unsigned long long trace_ctx_Long_AsUnsignedLongLongMask(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 91);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    unsigned long long res = HPyLong_AsUnsignedLongLongMask(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 91, cr, &_ts_start, &_ts_end);
    return res;
}

size_t trace_ctx_Long_AsSize_t(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 92);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    size_t res = HPyLong_AsSize_t(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 92, cr, &_ts_start, &_ts_end);
    return res;
}

HPy_ssize_t trace_ctx_Long_AsSsize_t(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 93);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_ssize_t res = HPyLong_AsSsize_t(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 93, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_Long_AsVoidPtr(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 94);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = HPyLong_AsVoidPtr(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 94, cr, &_ts_start, &_ts_end);
    return res;
}

double trace_ctx_Long_AsDouble(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 95);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    double res = HPyLong_AsDouble(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 95, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Float_FromDouble(HPyContext *tctx, double v)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 96);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyFloat_FromDouble(uctx, v);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 96, cr, &_ts_start, &_ts_end);
    return res;
}

double trace_ctx_Float_AsDouble(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 97);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    double res = HPyFloat_AsDouble(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 97, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Bool_FromLong(HPyContext *tctx, long v)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 98);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyBool_FromLong(uctx, v);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 98, cr, &_ts_start, &_ts_end);
    return res;
}

HPy_ssize_t trace_ctx_Length(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 99);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_ssize_t res = HPy_Length(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 99, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Number_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 100);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyNumber_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 100, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Add(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 101);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Add(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 101, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Subtract(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 102);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Subtract(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 102, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Multiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 103);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Multiply(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 103, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_MatrixMultiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 104);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_MatrixMultiply(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 104, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_FloorDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 105);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_FloorDivide(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 105, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_TrueDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 106);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_TrueDivide(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 106, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Remainder(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 107);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Remainder(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 107, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Divmod(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 108);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Divmod(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 108, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Power(HPyContext *tctx, HPy h1, HPy h2, HPy h3)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 109);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Power(uctx, h1, h2, h3);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 109, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Negative(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 110);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Negative(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 110, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Positive(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 111);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Positive(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 111, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Absolute(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 112);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Absolute(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 112, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Invert(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 113);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Invert(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 113, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Lshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 114);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Lshift(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 114, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Rshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 115);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Rshift(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 115, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_And(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 116);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_And(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 116, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Xor(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 117);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Xor(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 117, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Or(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 118);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Or(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 118, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Index(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 119);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Index(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 119, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Long(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 120);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Long(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 120, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Float(HPyContext *tctx, HPy h1)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 121);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Float(uctx, h1);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 121, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceAdd(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 122);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceAdd(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 122, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceSubtract(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 123);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceSubtract(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 123, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceMultiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 124);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceMultiply(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 124, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceMatrixMultiply(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 125);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceMatrixMultiply(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 125, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceFloorDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 126);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceFloorDivide(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 126, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceTrueDivide(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 127);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceTrueDivide(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 127, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceRemainder(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 128);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceRemainder(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 128, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlacePower(HPyContext *tctx, HPy h1, HPy h2, HPy h3)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 129);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlacePower(uctx, h1, h2, h3);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 129, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceLshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 130);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceLshift(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 130, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceRshift(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 131);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceRshift(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 131, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceAnd(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 132);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceAnd(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 132, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceXor(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 133);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceXor(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 133, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_InPlaceOr(HPyContext *tctx, HPy h1, HPy h2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 134);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_InPlaceOr(uctx, h1, h2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 134, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Callable_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 135);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyCallable_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 135, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_CallTupleDict(HPyContext *tctx, HPy callable, HPy args, HPy kw)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 136);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_CallTupleDict(uctx, callable, args, kw);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 136, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Err_SetString(HPyContext *tctx, HPy h_type, const char *message)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 138);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyErr_SetString(uctx, h_type, message);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 138, cr, &_ts_start, &_ts_end);
}

void trace_ctx_Err_SetObject(HPyContext *tctx, HPy h_type, HPy h_value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 139);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyErr_SetObject(uctx, h_type, h_value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 139, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_Err_SetFromErrnoWithFilename(HPyContext *tctx, HPy h_type, const char *filename_fsencoded)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 140);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyErr_SetFromErrnoWithFilename(uctx, h_type, filename_fsencoded);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 140, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Err_SetFromErrnoWithFilenameObjects(HPyContext *tctx, HPy h_type, HPy filename1, HPy filename2)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 141);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyErr_SetFromErrnoWithFilenameObjects(uctx, h_type, filename1, filename2);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 141, cr, &_ts_start, &_ts_end);
}

int trace_ctx_Err_Occurred(HPyContext *tctx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 142);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyErr_Occurred(uctx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 142, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Err_ExceptionMatches(HPyContext *tctx, HPy exc)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 143);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyErr_ExceptionMatches(uctx, exc);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 143, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Err_NoMemory(HPyContext *tctx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 144);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyErr_NoMemory(uctx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 144, cr, &_ts_start, &_ts_end);
}

void trace_ctx_Err_Clear(HPyContext *tctx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 145);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyErr_Clear(uctx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 145, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_Err_NewException(HPyContext *tctx, const char *name, HPy base, HPy dict)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 146);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyErr_NewException(uctx, name, base, dict);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 146, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Err_NewExceptionWithDoc(HPyContext *tctx, const char *name, const char *doc, HPy base, HPy dict)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 147);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyErr_NewExceptionWithDoc(uctx, name, doc, base, dict);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 147, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Err_WarnEx(HPyContext *tctx, HPy category, const char *message, HPy_ssize_t stack_level)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 148);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyErr_WarnEx(uctx, category, message, stack_level);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 148, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Err_WriteUnraisable(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 149);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyErr_WriteUnraisable(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 149, cr, &_ts_start, &_ts_end);
}

int trace_ctx_IsTrue(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 150);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_IsTrue(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 150, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Type_FromSpec(HPyContext *tctx, HPyType_Spec *spec, HPyType_SpecParam *params)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 151);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyType_FromSpec(uctx, spec, params);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 151, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Type_GenericNew(HPyContext *tctx, HPy type, HPy *args, HPy_ssize_t nargs, HPy kw)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 152);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyType_GenericNew(uctx, type, args, nargs, kw);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 152, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_GetAttr(HPyContext *tctx, HPy obj, HPy name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 153);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_GetAttr(uctx, obj, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 153, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_GetAttr_s(HPyContext *tctx, HPy obj, const char *name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 154);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_GetAttr_s(uctx, obj, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 154, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_HasAttr(HPyContext *tctx, HPy obj, HPy name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 155);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_HasAttr(uctx, obj, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 155, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_HasAttr_s(HPyContext *tctx, HPy obj, const char *name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 156);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_HasAttr_s(uctx, obj, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 156, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_SetAttr(HPyContext *tctx, HPy obj, HPy name, HPy value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 157);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_SetAttr(uctx, obj, name, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 157, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_SetAttr_s(HPyContext *tctx, HPy obj, const char *name, HPy value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 158);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_SetAttr_s(uctx, obj, name, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 158, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_GetItem(HPyContext *tctx, HPy obj, HPy key)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 159);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_GetItem(uctx, obj, key);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 159, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_GetItem_i(HPyContext *tctx, HPy obj, HPy_ssize_t idx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 160);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_GetItem_i(uctx, obj, idx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 160, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_GetItem_s(HPyContext *tctx, HPy obj, const char *key)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 161);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_GetItem_s(uctx, obj, key);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 161, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Contains(HPyContext *tctx, HPy container, HPy key)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 162);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_Contains(uctx, container, key);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 162, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_SetItem(HPyContext *tctx, HPy obj, HPy key, HPy value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 163);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_SetItem(uctx, obj, key, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 163, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_SetItem_i(HPyContext *tctx, HPy obj, HPy_ssize_t idx, HPy value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 164);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_SetItem_i(uctx, obj, idx, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 164, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_SetItem_s(HPyContext *tctx, HPy obj, const char *key, HPy value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 165);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_SetItem_s(uctx, obj, key, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 165, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_DelItem(HPyContext *tctx, HPy obj, HPy key)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 236);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_DelItem(uctx, obj, key);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 236, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_DelItem_i(HPyContext *tctx, HPy obj, HPy_ssize_t idx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 237);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_DelItem_i(uctx, obj, idx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 237, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_DelItem_s(HPyContext *tctx, HPy obj, const char *key)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 238);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_DelItem_s(uctx, obj, key);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 238, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Type(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 166);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Type(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 166, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_TypeCheck(HPyContext *tctx, HPy obj, HPy type)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 167);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_TypeCheck(uctx, obj, type);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 167, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Is(HPyContext *tctx, HPy obj, HPy other)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 168);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_Is(uctx, obj, other);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 168, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Object(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 169);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Object(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 169, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Legacy(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 170);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Legacy(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 170, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Type(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 229);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Type(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 229, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Long(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 230);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Long(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 230, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Float(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 231);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Float(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 231, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Unicode(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 232);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Unicode(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 232, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_Tuple(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 233);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_Tuple(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 233, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_AsStruct_List(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 234);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = _HPy_AsStruct_List(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 234, cr, &_ts_start, &_ts_end);
    return res;
}

HPyType_BuiltinShape trace_ctx_Type_GetBuiltinShape(HPyContext *tctx, HPy h_type)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 235);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyType_BuiltinShape res = _HPyType_GetBuiltinShape(uctx, h_type);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 235, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_New(HPyContext *tctx, HPy h_type, void **data)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 171);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = _HPy_New(uctx, h_type, data);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 171, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Repr(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 172);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Repr(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 172, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Str(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 173);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Str(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 173, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_ASCII(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 174);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_ASCII(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 174, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Bytes(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 175);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_Bytes(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 175, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_RichCompare(HPyContext *tctx, HPy v, HPy w, int op)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 176);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_RichCompare(uctx, v, w, op);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 176, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_RichCompareBool(HPyContext *tctx, HPy v, HPy w, int op)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 177);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPy_RichCompareBool(uctx, v, w, op);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 177, cr, &_ts_start, &_ts_end);
    return res;
}

HPy_hash_t trace_ctx_Hash(HPyContext *tctx, HPy obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 178);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_hash_t res = HPy_Hash(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 178, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Bytes_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 179);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyBytes_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 179, cr, &_ts_start, &_ts_end);
    return res;
}

HPy_ssize_t trace_ctx_Bytes_Size(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 180);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_ssize_t res = HPyBytes_Size(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 180, cr, &_ts_start, &_ts_end);
    return res;
}

HPy_ssize_t trace_ctx_Bytes_GET_SIZE(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 181);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_ssize_t res = HPyBytes_GET_SIZE(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 181, cr, &_ts_start, &_ts_end);
    return res;
}

char *trace_ctx_Bytes_AsString(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 182);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    char * res = HPyBytes_AsString(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 182, cr, &_ts_start, &_ts_end);
    return res;
}

char *trace_ctx_Bytes_AS_STRING(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 183);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    char * res = HPyBytes_AS_STRING(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 183, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Bytes_FromString(HPyContext *tctx, const char *v)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 184);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyBytes_FromString(uctx, v);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 184, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Bytes_FromStringAndSize(HPyContext *tctx, const char *v, HPy_ssize_t len)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 185);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyBytes_FromStringAndSize(uctx, v, len);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 185, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_FromString(HPyContext *tctx, const char *utf8)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 186);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_FromString(uctx, utf8);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 186, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Unicode_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 187);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyUnicode_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 187, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_AsASCIIString(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 188);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_AsASCIIString(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 188, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_AsLatin1String(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 189);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_AsLatin1String(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 189, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_AsUTF8String(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 190);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_AsUTF8String(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 190, cr, &_ts_start, &_ts_end);
    return res;
}

const char *trace_ctx_Unicode_AsUTF8AndSize(HPyContext *tctx, HPy h, HPy_ssize_t *size)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 191);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    const char * res = HPyUnicode_AsUTF8AndSize(uctx, h, size);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 191, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_FromWideChar(HPyContext *tctx, const wchar_t *w, HPy_ssize_t size)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 192);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_FromWideChar(uctx, w, size);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 192, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_DecodeFSDefault(HPyContext *tctx, const char *v)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 193);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_DecodeFSDefault(uctx, v);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 193, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_DecodeFSDefaultAndSize(HPyContext *tctx, const char *v, HPy_ssize_t size)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 194);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_DecodeFSDefaultAndSize(uctx, v, size);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 194, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_EncodeFSDefault(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 195);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_EncodeFSDefault(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 195, cr, &_ts_start, &_ts_end);
    return res;
}

HPy_UCS4 trace_ctx_Unicode_ReadChar(HPyContext *tctx, HPy h, HPy_ssize_t index)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 196);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_UCS4 res = HPyUnicode_ReadChar(uctx, h, index);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 196, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_DecodeASCII(HPyContext *tctx, const char *s, HPy_ssize_t size, const char *errors)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 197);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_DecodeASCII(uctx, s, size, errors);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 197, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Unicode_DecodeLatin1(HPyContext *tctx, const char *s, HPy_ssize_t size, const char *errors)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 198);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyUnicode_DecodeLatin1(uctx, s, size, errors);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 198, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_List_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 199);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyList_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 199, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_List_New(HPyContext *tctx, HPy_ssize_t len)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 200);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyList_New(uctx, len);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 200, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_List_Append(HPyContext *tctx, HPy h_list, HPy h_item)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 201);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyList_Append(uctx, h_list, h_item);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 201, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Dict_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 202);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyDict_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 202, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Dict_New(HPyContext *tctx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 203);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyDict_New(uctx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 203, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Tuple_Check(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 204);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyTuple_Check(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 204, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Tuple_FromArray(HPyContext *tctx, HPy items[], HPy_ssize_t n)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 205);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyTuple_FromArray(uctx, items, n);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 205, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Import_ImportModule(HPyContext *tctx, const char *name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 206);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyImport_ImportModule(uctx, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 206, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_Capsule_New(HPyContext *tctx, void *pointer, const char *name, HPyCapsule_Destructor *destructor)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 245);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyCapsule_New(uctx, pointer, name, destructor);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 245, cr, &_ts_start, &_ts_end);
    return res;
}

void *trace_ctx_Capsule_Get(HPyContext *tctx, HPy capsule, _HPyCapsule_key key, const char *name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 246);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    void * res = HPyCapsule_Get(uctx, capsule, key, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 246, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Capsule_IsValid(HPyContext *tctx, HPy capsule, const char *name)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 247);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyCapsule_IsValid(uctx, capsule, name);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 247, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Capsule_Set(HPyContext *tctx, HPy capsule, _HPyCapsule_key key, void *value)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 248);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyCapsule_Set(uctx, capsule, key, value);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 248, cr, &_ts_start, &_ts_end);
    return res;
}

HPy trace_ctx_FromPyObject(HPyContext *tctx, cpy_PyObject *obj)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 207);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPy_FromPyObject(uctx, obj);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 207, cr, &_ts_start, &_ts_end);
    return res;
}

cpy_PyObject *trace_ctx_AsPyObject(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 208);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    cpy_PyObject * res = HPy_AsPyObject(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 208, cr, &_ts_start, &_ts_end);
    return res;
}

HPyListBuilder trace_ctx_ListBuilder_New(HPyContext *tctx, HPy_ssize_t initial_size)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 210);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyListBuilder res = HPyListBuilder_New(uctx, initial_size);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 210, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_ListBuilder_Set(HPyContext *tctx, HPyListBuilder builder, HPy_ssize_t index, HPy h_item)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 211);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyListBuilder_Set(uctx, builder, index, h_item);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 211, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_ListBuilder_Build(HPyContext *tctx, HPyListBuilder builder)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 212);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyListBuilder_Build(uctx, builder);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 212, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_ListBuilder_Cancel(HPyContext *tctx, HPyListBuilder builder)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 213);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyListBuilder_Cancel(uctx, builder);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 213, cr, &_ts_start, &_ts_end);
}

HPyTupleBuilder trace_ctx_TupleBuilder_New(HPyContext *tctx, HPy_ssize_t initial_size)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 214);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyTupleBuilder res = HPyTupleBuilder_New(uctx, initial_size);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 214, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_TupleBuilder_Set(HPyContext *tctx, HPyTupleBuilder builder, HPy_ssize_t index, HPy h_item)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 215);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyTupleBuilder_Set(uctx, builder, index, h_item);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 215, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_TupleBuilder_Build(HPyContext *tctx, HPyTupleBuilder builder)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 216);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyTupleBuilder_Build(uctx, builder);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 216, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_TupleBuilder_Cancel(HPyContext *tctx, HPyTupleBuilder builder)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 217);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyTupleBuilder_Cancel(uctx, builder);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 217, cr, &_ts_start, &_ts_end);
}

HPyTracker trace_ctx_Tracker_New(HPyContext *tctx, HPy_ssize_t size)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 218);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyTracker res = HPyTracker_New(uctx, size);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 218, cr, &_ts_start, &_ts_end);
    return res;
}

int trace_ctx_Tracker_Add(HPyContext *tctx, HPyTracker ht, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 219);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    int res = HPyTracker_Add(uctx, ht, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 219, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Tracker_ForgetAll(HPyContext *tctx, HPyTracker ht)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 220);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyTracker_ForgetAll(uctx, ht);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 220, cr, &_ts_start, &_ts_end);
}

void trace_ctx_Tracker_Close(HPyContext *tctx, HPyTracker ht)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 221);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyTracker_Close(uctx, ht);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 221, cr, &_ts_start, &_ts_end);
}

void trace_ctx_Field_Store(HPyContext *tctx, HPy target_object, HPyField *target_field, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 222);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyField_Store(uctx, target_object, target_field, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 222, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_Field_Load(HPyContext *tctx, HPy source_object, HPyField source_field)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 223);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyField_Load(uctx, source_object, source_field);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 223, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_ReenterPythonExecution(HPyContext *tctx, HPyThreadState state)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 224);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy_ReenterPythonExecution(uctx, state);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 224, cr, &_ts_start, &_ts_end);
}

HPyThreadState trace_ctx_LeavePythonExecution(HPyContext *tctx)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 225);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyThreadState res = HPy_LeavePythonExecution(uctx);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 225, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Global_Store(HPyContext *tctx, HPyGlobal *global, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 226);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPyGlobal_Store(uctx, global, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 226, cr, &_ts_start, &_ts_end);
}

HPy trace_ctx_Global_Load(HPyContext *tctx, HPyGlobal global)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 227);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    HPy res = HPyGlobal_Load(uctx, global);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 227, cr, &_ts_start, &_ts_end);
    return res;
}

void trace_ctx_Dump(HPyContext *tctx, HPy h)
{
    HPyTraceInfo *info = hpy_trace_on_enter(tctx, 228);
    HPyContext *uctx = info->uctx;
    _HPyTime_t _ts_start, _ts_end;
    int cr = get_monotonic_clock(&_ts_start);
    _HPy_Dump(uctx, h);
    cr += get_monotonic_clock(&_ts_end);
    hpy_trace_on_exit(info, 228, cr, &_ts_start, &_ts_end);
}

