
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by tools/autogen.py from tools/public_api.h.
   Run this to regenerate:
       make autogen

*/

typedef enum {
    HPy_nb_absolute = 6,
    HPy_nb_add = 7,
    HPy_nb_and = 8,
    HPy_nb_divmod = 10,
    HPy_nb_float = 11,
    HPy_nb_floor_divide = 12,
    HPy_nb_index = 13,
    HPy_nb_int = 26,
    HPy_nb_invert = 27,
    HPy_nb_lshift = 28,
    HPy_nb_multiply = 29,
    HPy_nb_negative = 30,
    HPy_nb_or = 31,
    HPy_nb_positive = 32,
    HPy_nb_remainder = 34,
    HPy_nb_rshift = 35,
    HPy_nb_subtract = 36,
    HPy_nb_true_divide = 37,
    HPy_nb_xor = 38,
    HPy_sq_item = 44,
    HPy_tp_init = 60,
    HPy_tp_new = 65,
    HPy_tp_repr = 66,
    HPy_nb_matrix_multiply = 75,
    HPy_tp_destroy = 1000,
} HPySlot_Slot;

#define _HPySlot_SIG__HPy_nb_absolute HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_add HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_and HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_divmod HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_float HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_floor_divide HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_index HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_int HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_invert HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_lshift HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_multiply HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_negative HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_or HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_positive HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_nb_remainder HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_rshift HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_subtract HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_true_divide HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_nb_xor HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_sq_item HPyFunc_SSIZEARGFUNC
#define _HPySlot_SIG__HPy_tp_init HPyFunc_INITPROC
#define _HPySlot_SIG__HPy_tp_new HPyFunc_KEYWORDS
#define _HPySlot_SIG__HPy_tp_repr HPyFunc_REPRFUNC
#define _HPySlot_SIG__HPy_nb_matrix_multiply HPyFunc_BINARYFUNC
#define _HPySlot_SIG__HPy_tp_destroy HPyFunc_DESTROYFUNC
