
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by tools/autogen.py from tools/public_api.h.
   Run this to regenerate:
       make autogen

*/

typedef enum {
    HPy_nb_absolute = 6,
    HPy_sq_item = 44,
    HPy_tp_init = 60,
    HPy_tp_new = 65,
    HPy_tp_repr = 66,
    HPy_tp_destroy = 1000,
} HPySlot_Slot;

#define _HPySlot_SIG__HPy_nb_absolute HPyFunc_UNARYFUNC
#define _HPySlot_SIG__HPy_sq_item HPyFunc_SSIZEARGFUNC
#define _HPySlot_SIG__HPy_tp_init HPyFunc_INITPROC
#define _HPySlot_SIG__HPy_tp_new HPyFunc_KEYWORDS
#define _HPySlot_SIG__HPy_tp_repr HPyFunc_REPRFUNC
#define _HPySlot_SIG__HPy_tp_destroy HPyFunc_DESTROYFUNC
