
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by tools/autogen.py from tools/public_api.h.
   Run this to regenerate:
       make autogen

*/

#define _HPyFunc_TRAMPOLINE_HPyFunc_UNARY(SYM, IMPL) \
    static cpy_PyObject *SYM(cpy_PyObject *arg) \
    { \
        return _h2py(IMPL(_HPyGetContext(), _py2h(arg))); \
    }
#define _HPyFunc_TRAMPOLINE_HPyFunc_REPR(SYM, IMPL) \
    static cpy_PyObject *SYM(cpy_PyObject *arg) \
    { \
        return _h2py(IMPL(_HPyGetContext(), _py2h(arg))); \
    }
