C_DISCLAIMER = """
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by tools/autogen.py from tools/public_api.h.
   Run this to regenerate:
       make autogen

   TEMPORARY LINE TO PLAY WITH GITHUB DIFFS
*/
"""

class AutoGenFile:
    LANGUAGE = 'C'
    PATH = None
    DISCLAIMER = None

    def __init__(self, api):
        if self.DISCLAIMER is None and self.LANGUAGE == 'C':
            self.DISCLAIMER = C_DISCLAIMER
        self.api = api

    def generate(self):
        raise NotImplementedError

    def write(self, root):
        with root.join(self.PATH).open('w') as f:
            if self.DISCLAIMER is not None:
                f.write(self.DISCLAIMER)
                f.write('\n')
            f.write(self.generate())
            f.write('\n')
