from .autogenfile import AutoGenFile

RST_DISCLAIMER = """
.. note: DO NOT EDIT THIS FILE!
    This file is automatically generated by {clsname}
    See also hpy.tools.autogen and hpy/tools/public_api.h

    Run this to regenerate:
        make autogen
"""

class AutoGenRstFile(AutoGenFile):
    LANGUAGE = 'rst'
    PATH = None
    DISCLAIMER = None

    def __init__(self, api):
        if self.DISCLAIMER is None and self.LANGUAGE == 'rst':
            self.DISCLAIMER = RST_DISCLAIMER
        self.api = api


class autogen_function_index(AutoGenRstFile):
    PATH = 'docs/api-reference/function-index.rst'
    LANGUAGE = 'rst'

    def generate(self):
        lines = []
        w = lines.append
        w('HPy Core API Function Index')
        w('###########################')
        w('')
        for func in self.api.functions:
            if func.name[0] != '_':
                w(f'* :c:func:`{func.name}`')
        return '\n'.join(lines)
