
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by tools/autogen.py from tools/public_api.h.
   Run this to regenerate:
       make autogen

*/

struct _HPyContext_s global_ctx = {
    .ctx_version = 1,
    .ctx_Module_Create = &ctx_Module_Create,
    .ctx_None_Get = &ctx_None_Get,
    .ctx_Dup = &ctx_Dup,
    .ctx_Close = &ctx_Close,
    .ctx_Long_FromLong = &ctx_Long_FromLong,
    .ctx_Long_AsLong = &ctx_Long_AsLong,
    .ctx_Arg_Parse = &ctx_Arg_Parse,
    .ctx_Number_Add = &ctx_Number_Add,
    .ctx_Unicode_FromString = &ctx_Unicode_FromString,
    .ctx_FromPyObject = &ctx_FromPyObject,
    .ctx_AsPyObject = &ctx_AsPyObject,
    .ctx_CallRealFunctionFromTrampoline = &ctx_CallRealFunctionFromTrampoline,
};
