---
name: tests

on: [pull_request]

jobs:
  main_tests:
    name: Main tests ${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      # Duplicate changes to this matrix to 'poc_tests'
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14]
        python-version: ['3.10']
        compiler: [""]

    steps:
      - uses: actions/checkout@v4

      # - template: azure-templates/ccache.yml
      #   parameters:
      #     pythonVersion: $(python.version)
      # - template: azure-templates/python.yml
      #   parameters:
      #     pythonVersion: $(python.version)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install/Upgrade Python dependencies
        run: python -m pip install --upgrade pip wheel 'setuptools>=60.2'

      - name: Build
        run: |
          make
          python -m pip install .

      - if: ${{ matrix.compiler }}
        # Only set the compiler for the tests, not for the build
        run: echo "CC=${{ matrix.compiler }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python -m pip install pytest pytest-xdist filelock
          python -m pytest --basetemp=.tmpdir --durations=16 -n auto test/
