# This Action looks for typos in the codebase using codespell
# and provide users with intuitive GitHub Annotations.
# https://github.com/codespell-project/codespell#readme
name: codespell
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: codespell-project/actions-codespell@v2
