---
name: Release to PyPI

on: [pull_request]
  # release:
  #   types: [created]

jobs:
  build_sdist:
    name: Build source package (sdist)
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Install/Upgrade Python dependencies
      run: python -m pip install --upgrade pip wheel

    - name: Build and install Python source package
      run: |
        python setup.py sdist
        python -m pip install dist/*.tar.gz

    - name: Run tests
      run: |
        pip install pytest pytest-xdist
        pytest -n auto test/

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz


  build_bdist:
    name: Build binary packages (.whl)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    # for other architectures, see: https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.1.1
      env:
        CIBW_TEST_REQUIRES: pytest pytest-xdist
        CIBW_TEST_COMMAND: pytest -n auto {package}/test/

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl


  upload_pypi:
    name: Publish packages to PyPI
    # only publish packages once everything is successful
    needs: [build_bdist, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
